package types

const TRANSFER = "transfer"
const ONE_PURSE_TRANSACTION = "one-purse-transfer"
const WITHDRAW = "withdraw"
const DEPOSIT = "deposit"
const EXCHANGE = "exchange"
const REQUEST = "request"
const PAY = "pay"
const PAYMENT_REQUEST = "payment requested"
const PAYMENT_RECEIVED = "payment received"
const TRANSACTION_MATCH = "you have been matched to a transaction"
const DEACTIVATE = "deactivate"
const ACTIVATE = "activate"
const APPROVE = "approve"
const REJECT = "reject"
const APPROVED = "approved"
const REJECTED = "rejected"
const SINGLE = "single"
const REQUIRE_NEW_PASSWORD = "require-new-password"
const ADMIN_LOGIN = "admin-login"
const USER_LOGIN = "user-login"
const AGENT_LOGIN = "agent-login"
