package types

const TRANSFER = "transfer"
const ONE_PURSE_TRANSACTION = "one-purse-transfer"
const WITHDRAW = "withdraw"
const DEPOSIT = "deposit"
const EXCHANGE = "exchange"
const REQUEST = "request"
const PAY = "pay"
const PAYMENT_REQUEST = "payment requested"
const PAYMENT_RECEIVED = "payment received"
const TRANSACTION_MATCH = "you have been matched to a transaction"
const ACCEPT = "accept"
const USER = "user"
const AGENT = "agent"
